/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductUpdateDto { 
    sku: string;
    active: boolean;
    name: string;
    image: string;
    description: string;
    price: number;
    stock: number;
    categoryId?: number;
}

