/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductShowDto { 
    id: number;
    sku: string;
    name: string;
    image: string;
    price: number;
    stock: number;
}

