/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserShowDto { 
    id?: number;
    firstName?: string;
    lastName?: string;
    street?: string;
    zip?: string;
    city?: string;
    country?: string;
    phone?: string;
    mobilePhone?: string;
    email?: string;
    isAdmin?: boolean;
}

